name: Build And Upload Extension Zip Via Artifact

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - run: yarn install

      - name: Patch version for each merge dry run
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.36.0
        env:
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          DEFAULT_BUMP: patch
          WITH_V: true
          VERBOSE: true

      - run: yarn build

      - name: Display manifest
        run: cat dist/manifest.json
        shell: bash

      - run: yarn run build:extension

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*
          name: extension.zip
          if-no-files-found: error

      - name: Patch version for each merge real
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.36.0
        env:
          DRY_RUN: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          DEFAULT_BUMP: patch
          WITH_V: true
          VERBOSE: true

      - name: Upload & release
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: dist/extension.zip
          extension-id: kgbclpndllpkdhmeihpfbfehkdbpnlfh
          client-id: ${{ secrets.PUBLISH_CLIENT_ID }}
          client-secret: ${{ secrets.PUBLISH_CLIENT_SECRET }}
          refresh-token: ${{ secrets.PUBLISH_REFRESH_TOKEN }}
